#!/bin/bash

# A script to compare our mirror to the BAS mirror 1 month at a time going back 12 months, and download any
# rawacf files that we are missing. Runs weekly.

curdate=$(date +%Y%m%d)
startdate=$(date -d "$curdate - 1 year" +%Y%m)
# Start date is the 1st of the month, 1 year ago
startdate="${startdate}01"
d=${startdate}
# End date is the 1st of the month, now
enddate=$(date +%Y%m)
enddate="${enddate}01"
echo "Date range: ${startdate} - ${enddate}"

# Loop will end before we get to the current month
# Last iteration will be the month before the current month
while [ "$d" != "${enddate}" ]
do 
	yearmonth=$(date -d "$d" +%Y%m)
	/home/dataman/data_flow/mirror/sync_mirror_data.sh /data/holding/BAS BAS ${yearmonth}
  d=$(date -d "$d + 1 month" +%Y%m%d)
done

