#!/bin/bash

# A script to compare our mirror to the BAS mirror 1 month at a time going back to January 2006, and download any
# rawacf files that we are missing. Runs monthly.

# Start date is the beginning of 2006
startdate=20060101
d=${startdate}
today=$(date +%Y%m%d)
# End date is the 1st of the current month
enddate=$(date +%Y%m)
enddate="${enddate}01"
echo "Date range: ${startdate} - ${enddate}"

# Loop ends before current month
while [ "$d" != "${enddate}" ]
do 
	yearmonth=$(date -d "$d" +%Y%m)
	/home/dataman/data_flow/mirror/sync_mirror_data.sh /data/holding/BAS BAS ${yearmonth}
  d=$(date -d "$d + 1 month" +%Y%m%d)
done

# Update mirror comparison
CMP_DIR=/home/dataman/Documents/mirror_comparison_${today}/
HASHES_DIRS=/home/dataman/tmp_hashes_usask/${today}.*

mkdir -p ${CMP_DIR}
find ${HASHES_DIRS} -name '*data.different' -exec cat '{}' \; > ${CMP_DIR}/bas.different
find ${HASHES_DIRS} -name '*data.blocked' -exec cat '{}' \; > ${CMP_DIR}/bas.blocked
find ${HASHES_DIRS} -name '*data.not_at_usask' -exec cat '{}' \; > ${CMP_DIR}/bas.not_at_usask
find ${HASHES_DIRS} -name '*data.not_at_bas' -exec cat '{}' \; > ${CMP_DIR}/bas.not_at_bas
find ${HASHES_DIRS} -name '*data.failed' -exec cat '{}' \; > ${CMP_DIR}/bas.failed

mkdir -p ${CMP_DIR}/sorted
sort -k2 ${CMP_DIR}/bas.different > ${CMP_DIR}/sorted/bas_different
sort -k2 ${CMP_DIR}/bas.not_at_bas > ${CMP_DIR}/sorted/bas_not_at_bas
sort ${CMP_DIR}/bas.not_at_usask > ${CMP_DIR}/sorted/bas_not_at_usask
sort ${CMP_DIR}/bas.failed > ${CMP_DIR}/sorted/bas_failed
sort ${CMP_DIR}/bas.blocked > ${CMP_DIR}/sorted/bas_blocked

