#!/bin/bash
# Copyright 2019 SuperDARN Canada, University of Saskatchewan
# Author: Dieter Andre
#
# Last Edited: October 2022 by Theo Kolkman
# Refactored for inotify usage
#
# A singleton script to transfer rawacf dmap and hdf5 files from site NAS to superdarn-cssdp on 
# campus. Files are copied first and removed once copy is confirmed to be successful. 
#
# To modify this script to transfer files from a local Site-Linux directory instead of the NAS:
#   1. Change DATA_DIR to the directory on the Site-Linux computer Borealis data is stored. This 
#      directory must have the same structure as the NAS directory (rawacf_array and rawacf_dmap
#	   directories specifically)
#   2. Specify which files are to be transferred by add/removing the RADARID of the respective site 
#      from the *.SITES arrays
#
# Dependencies:
# 	- RADARID and SDCOPY set as environment variables in ${HOME}/.bashrc
#	- ssh link established between Site-Linux and SDCOPY computers
#	- ssh link established between Site-Linux and TELEMETRY computers
#
# This script should be run via an inotify daemon triggerring when the previous data flow script 
# finishes execution

###################################################################################################

# Specify error behaviour
set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

source "${HOME}/.bashrc" # source the RADARID, SDCOPY and other things
source "${HOME}/data_flow/library/data_flow_functions.sh" # Load dataflow functions

###################################################################################################

# Specify which sites will transfer each file type
readonly DMAP_SITES=("sas" "pgr" "inv")
readonly HDF5_SITES=("sas" "pgr" "inv" "cly" "rkn")

# Location rawacf files are transferring from
readonly DATA_DIR="/borealis_nfs/borealis_data"
readonly DMAP_SOURCE="${DATA_DIR}/rawacf_dmap/"
readonly ARRAY_SOURCE="${DATA_DIR}/rawacf_array/"

# If site isn't transferring dmap files, send to holding directory for campus conversion
if [[ ! " ${DMAP_SITES[*]} " =~ " ${RADARID} " ]]; then
	readonly DEST="/sddata/${RADARID}_holding_dir"
else
	readonly DEST="/sddata/${RADARID}_data/"
fi

# Create log file. New file created daily
readonly LOGGING_DIR="${HOME}/logs/rsync_to_campus/$(date +%Y)/$(date +%m)"
mkdir --parents $LOGGING_DIR
readonly LOGFILE="${LOGGING_DIR}/$(date +%Y%m%d).rsync_to_campus.log"
readonly SUMMARY_DIR="${HOME}/logs/rsync_to_campus/summary/$(date +%Y)/$(date +%m)"
mkdir --parents $SUMMARY_DIR
readonly SUMMARY_FILE="${SUMMARY_DIR}/$(date -u +%Y%m%d).rsync_to_campus_summary.log"

# Define variables needed to rsync summary files back to campus
readonly TELEMETRY_DIR="/home/telemetry/data_flow_logs/${RADARID}/rsync_to_campus"
readonly TELEMETRY="telemetry@chapman.usask.ca"
readonly RSH="ssh -p 2222"

###################################################################################################

# Redirect all stdout and sterr in this script to $LOGFILE
exec &>> $LOGFILE # Redirect STDOUT and STDERR to $LOGFILE

printf "################################################################################\n\n" | tee --append $SUMMARY_FILE

# Date in UTC format for logging
printf "Executing $0 on $(hostname)\n" | tee --append $SUMMARY_FILE
date --utc "+%Y%m%d %H:%M:%S UTC" | tee --append $SUMMARY_FILE

# Ensure that only a single instance of this script runs.
if pidof -o %PPID -x -- "$(basename -- $0)" > /dev/null; then
	printf "Error: Script $0 is already running. Exiting...\n"
	exit 1
fi

printf "Transferring from: $DATA_DIR\n" | tee --append $SUMMARY_FILE
printf "Transferring to: $SDCOPY:$DEST\n\n" | tee --append $SUMMARY_FILE

# Check if this site is transferring dmaps to campus
if [[ " ${DMAP_SITES[*]} " =~ " ${RADARID} " ]]; then
	# Find all dmap files to transfer
	files=$(find ${DMAP_SOURCE} -name '*rawacf.bz2' -printf '%p\n')

	if [[ -n $files ]]; then
		printf "\nPlacing following dmap files in ${SDCOPY}:${DEST}:\n"
		printf '%s\n' "${files[@]}"
	else
		printf "No dmap files found to be transferred.\n" | tee --append $SUMMARY_FILE
	fi

	# Transfer all files found
	for file in $files; do
		printf "\nTransferring: ${file} to ${SDCOPY}:${DEST}\n"
		rsync -av --append-verify --timeout=180 --rsh=ssh $file $SDCOPY:$DEST

		# Check if transfer was okay using the md5sum program, then remove the file if it matches
		verify_transfer $file "${DEST}/$(basename $file)" $SDCOPY
		return_value=$?
		if [[ $return_value -eq 0 ]]; then
			printf "Successfully transferred: ${file}\n" | tee --append $SUMMARY_FILE
			printf "Deleting file...\n"
			rm --verbose $file
		else
            # If file not transferred successfully, don't delete and try again next time
			printf "Transfer failed: ${file}\n" | tee --append $SUMMARY_FILE
			printf "File not deleted.\n"
		fi
	done
else
	printf "\nNot transferring any dmap files\n" | tee --append $SUMMARY_FILE
fi

# Check if this site is transferring HDF5 to campus
if [[ " ${HDF5_SITES[*]} " =~ " ${RADARID} " ]]; then
	# Find all hdf5 files to transfer
	files=`find ${ARRAY_SOURCE} -name '*rawacf.hdf5' -printf '%p\n'`

	if [[ -n $files ]]; then
		printf "\n\nPlacing following hdf5 files in ${SDCOPY}:${DEST}:\n"
		printf '%s\n' "${files[@]}"
	else
		printf "\nNo hdf5 files found to be transferred.\n" | tee --append $SUMMARY_FILE
	fi

	# Transfer all files found
	for file in $files; do
		printf "\nTransferring: ${file} to ${SDCOPY}:${DEST}\n"
		rsync -av --append-verify --timeout=180 --rsh=ssh $file $SDCOPY:$DEST

		# Check if transfer was okay using the md5sum program
		verify_transfer $file "${DEST}/$(basename $file)" $SDCOPY
		return_value=$?
		if [[ $return_value -eq 0 ]]; then
			printf "Successfully transferred: ${file}\n" | tee --append $SUMMARY_FILE
			printf "Deleting file...\n"
			rm --verbose $file
		else
            # If file not transferred successfully, don't delete and try again next time
			printf "Transfer failed: ${file}\n" | tee --append $SUMMARY_FILE
			printf "File not deleted.\n"
		fi
	done
else
	printf "\nNot transferring any HDF5 files\n" | tee --append $SUMMARY_FILE
fi

printf "\nFinished $(basename $0). End time: $(date --utc "+%Y%m%d %H:%M:%S UTC")\n\n" | tee --append $SUMMARY_FILE

# Sync summary log file with campus
printf "\nSyncing $SUMMARY_FILE to $TELEMETRY:$TELEMETRY_DIR\n\n"
rsync --archive --rsh="$RSH" $SUMMARY_FILE $TELEMETRY:$TELEMETRY_DIR

exit
