#!/bin/bash
# Copyright 2021 SuperDARN Canada, University of Saskatchewan
# Author: Marci Detwiller
#
# Last Edited: September 2022 by Theo Kolkman
# Refactored for inotify usage
#
# A script that uses pydarnio to convert Borealis files to SDARN DMap files
# Uses borealis_array_to_dmap.py script to convert already-restructured array files
# to dmap. 
# 
# to be run on SDCOPY for when bandwidth limits exist at site and both hdf5 and 
# dmap files will not be transferred 
#
# Dependencies:
#	- pydarnio installed in a virtualenv at $HOME/pydarnio-env
#
# Usage: ./convert_on_campus RADAR_ID
# Parameter RADAR_ID: [sas, pgr, rkn, inv, cly]
#
# This script should be run via an inotify daemon triggerring when the
# rsync_to_campus script finishes transferring files. To ensure only one instance
# runs for each site, use flock within the inotify daemon code

##############################################################################

# Specify error behaviour
set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

# source the RADAR_ID, SDCOPY and other things
# Load in function library
source "${HOME}/test_data_flow/data_flow/library/data_flow_functions.sh"

##############################################################################

RADAR_ID=$1

# Sites that have to convert dmap files on campus
# If a site isn't specified here, then this script is skipped and the flag
# for the next script is sent immediately
readonly SITES=("cly" "rkn" "lab") #TESTING

# Define directories
readonly DATA_DIR="/sddata/inotify_data_flow" # For SAS testing
# DATA_DIR=$HOME/testing/data_flow_testing/sddata #TESTING
readonly SOURCE="${DATA_DIR}/${RADAR_ID}_holding_dir" # this is the source
readonly RAWACF_DMAP_DEST="${DATA_DIR}/${RADAR_ID}_data"
readonly RAWACF_ARRAY_DEST="${DATA_DIR}/${RADAR_ID}_data"
readonly PROBLEM_FILES_DEST="${DATA_DIR}/conversion_failure"

# Flag received from rsync_to_nas script to trigger this script
readonly FLAG_IN="${HOME}/test_data_flow/data_flow/.inotify_watchdir/.rsync_to_campus_flag_${RADAR_ID}" # For SAS testing

# Location of inotify watch directory for flags on site linux
readonly FLAG_DEST="${HOME}/test_data_flow/data_flow/.inotify_watchdir" # For SAS testing

# Flag sent out to trigger rsync_to_campus script
readonly FLAG_OUT="${HOME}/test_data_flow/data_flow/.inotify_flags/.convert_on_campus_flag_${RADAR_ID}" # For SAS testing

# Create log file. New file created daily
readonly LOGGING_DIR="${HOME}/logs/convert_on_campus/$(date +%Y)/$(date +%m)"
mkdir --parents $LOGGING_DIR
readonly LOGFILE="${LOGGING_DIR}/${RADAR_ID}.$(date +%Y%m%d).convert_on_campus.log"
readonly  SUMMARY_DIR="${HOME}/logs/convert_on_campus/summary/$(date +%Y)/$(date +%m)"
mkdir --parents $SUMMARY_DIR
readonly SUMMARY_FILE="${SUMMARY_DIR}/${RADAR_ID}.$(date -u +%Y%m%d).convert_summary.log"

##############################################################################

# Redirect all stdout and sterr in this script to $LOGFILE
exec &>> $LOGFILE

printf "################################################################################\n\n" | tee --append $SUMMARY_FILE

printf "Executing $(basename "$0") on $(hostname)\n" | tee --append $SUMMARY_FILE
date --utc "+%Y%m%d %H:%M:%S UTC" | tee --append $SUMMARY_FILE

if [[ " ${SITES[*]} " =~ " ${RADAR_ID} " ]]; then

    RAWACF_CONVERT_FILES=$(find "${SOURCE}" -maxdepth 1 -name "*rawacf.hdf5" -type f)
    source "${HOME}/pydarnio-env/bin/activate"

    if [[ -n $RAWACF_CONVERT_FILES ]]; then
        printf "\nConverting the following files:\n"
        printf '%s\n' "${RAWACF_CONVERT_FILES[@]}"
    else
        printf "\nNo files to be converted.\n"
    fi

    for f in $RAWACF_CONVERT_FILES
    do
        printf "\nConverting ${f}\n"
        printf "python3 borealis_array_to_dmap.py $(basename ${f})\n"
        python3 "${HOME}/data_flow/test_data_flow/superdarn-cssdp/borealis_array_to_dmap.py" $f # For SAS testing
        ret=$?
        if [[ $ret -eq 0 ]]; then
            # move the resulting files if all was successful
            # then remove the source site file.
            dmap_file_start="${f%.rawacf.hdf5}"

            # remove last character(s) (slice_id)
            slice_id="${dmap_file_start##*.}"
            dmap_file_wo_slice_id="${dmap_file_start%${slice_id}}"

            ordinal_id="$(($slice_id + 97))"
            file_character=$(chr $ordinal_id)
            dmap_file="${dmap_file_wo_slice_id}${file_character}.rawacf.bz2"
            mv --verbose $dmap_file $RAWACF_DMAP_DEST
            mv --verbose $f $RAWACF_ARRAY_DEST
            printf "Successfully converted: ${f}\n" | tee --append $SUMMARY_FILE
        else
            printf "File failed to convert: ${f}\n" | tee --append $SUMMARY_FILE
            mv --verbose $f $PROBLEM_FILES_DEST
        fi
    done
fi

printf "\nTriggering next script via inotify...\n"
# Remove "flag" sent by convert_and_restructure to reset flag
# and allow inotify to see the next flag sent in
rm --verbose --force $FLAG_IN

# Send out "flag" to trigger next script with inotify
touch $FLAG_OUT
rsync -av --rsh=ssh $FLAG_OUT $FLAG_DEST

printf "\nFinished file conversion. End time: $(date --utc "+%Y%m%d %H:%M:%S UTC")\n\n" | tee --append $SUMMARY_FILE

exit
