#!/bin/bash
# Copyright 2024 SuperDARN Canada, University of Saskatchewan
# Author: Draven Galeschuk
#
# A script that searches the antennas iq plot directory of a  requested radar id and moves any
# files that are over 1 day old into a sorted archive.
#
# This script should be executed on campus for all SuperDARN radar sites. It can be run after all
# the other dataflow services in the campus daemon.
#
# Dependencies:
#
# Usage: ./archive_iq_plots RADAR_ID
# Parameter RADAR_ID: [sas, pgr, rkn, inv, cly]
#
###################################################################################################

source "${HOME}/data_flow/config.sh"  # Load common data flow variables

###################################################################################################

RADAR_ID=$1

if [[ $# -ne 1 ]]; then
    printf "Usage: ./archive_iq_plots RADAR_ID\n"
    exit 1
fi

if [[ ! " ${VALID_IDS[*]} " =~ " ${RADAR_ID} " ]]; then
    printf "\"$RADAR_ID\" is not a valid radar ID\n"
    exit 1
fi

# Define directories
readonly IQ_PLOTS="sddata/antennas_iq_plots/${RADAR_ID}_iq_plots/"
readonly ARCHIVE="${IQ_PLOTS}/archive/"

# Create latest archive directory if needed, based on time script was run
mkdir --parents "${ARCHIVE}/$(date +%Y/%m)"

# Create log file
readonly LOGGING_DIR="${HOME}/logs/archive_iq/$(date +%Y/%m)"
mkdir --parents $LOGGING_DIR
readonly LOGFILE="${LOGGING_DIR}/${RADAR_ID}.$(date +%Y%m%d).archive_iq.log"
readonly  SUMMARY_DIR="${HOME}/logs/archive_iq/summary/$(date +%Y/%m)"
mkdir --parents $SUMMARY_DIR
readonly SUMMARY_FILE="${SUMMARY_DIR}/${RADAR_ID}.$(date -u +%Y%m%d).archive_iq.log"

# Define convert parameters

RESOLUTION=160

###################################################################################################

exec &>> $LOGFILE # Redirect STDOUT and STDERR to $LOGFILE

printf "################################################################################\n\n" | tee --append $SUMMARY_FILE
printf "Executing $0 on $(hostname) for ${RADAR_ID}\n" | tee --append $SUMMARY_FILE
date --utc "+%Y%m%d %H:%M:%S UTC" | tee --append $SUMMARY_FILE

files=$(find ${IQ_PLOTS} -maxdepth 1 -type f -name "*.jpg")
now=$(date -u +"%s")

for file in ${files[@]}; do
  # strips away everything but the file time and format it to be parsed by date
  file_date=$(basename ${file} | sed 's/[^0-9][^0-9].*.//' | cut -d '.' -f 1,2 | tr . T)

  # Determine archive directory Year/Month destination for each file
  archive_dir="${ARCHIVE}/$(date -d ${file_date} +%Y/%m)/"

  # Move any files older than 24 hr to the archive directory
  cutoff=$(expr ${now} - 86400)
  if [[ $(date -u -d ${file_date} +"%s") < ${cutoff} ]]; then
    mv "${file}" "${archive_dir}"
  fi
done





