#!/bin/bash
# Copyright 2021 SuperDARN Canada, University of Saskatchewan
# Author: Marci Detwiller, Theodore Kolkman
#
# A script that uses pydarnio to convert Borealis rawacf files to SuperDARN DMap files. Uses the
# borealis_to_dmap.py script to convert already-restructured array files to dmap.
# 
# This script is executed on sdc-serv.usask.ca for all sites, but only performs conversions for
# sites specified in the CONVERT_ON_CAMPUS_SITES array. Only sites that don't transfer dmap
# files to campus should be specified in this array.
#
# Dependencies:
#	- pydarnio installed in a virtualenv at $HOME/pydarnio-env
#	- ssh link established between sdc-serv and TELEMETRY computers
#
# Usage: ./convert_on_campus RADAR_ID
# Parameter RADAR_ID: [sas, pgr, rkn, inv, cly]
#
# This script should be run via an inotify daemon triggerring when the previous data flow script 
# finishes execution. To ensure only one instance runs for each site, use flock within the inotify
# daemon code

###################################################################################################

source "${HOME}/data_flow/config.sh"  # Load common data flow variables
source "${HOME}/data_flow/library/data_flow_functions.sh"  # Load in function library
source "${HOME}/pydarnio-env/bin/activate"

###################################################################################################

RADAR_ID=$1

if [[ $# -ne 1 ]]; then
    printf "Usage: ./convert_on_campus RADAR_ID\n"
    exit 1
fi

if [[ ! " ${VALID_IDS[*]} " =~ " ${RADAR_ID} " ]]; then
    printf "\"$RADAR_ID\" is not a valid radar ID\n"
    exit 1
fi

# Sites that have to convert dmap files on campus are specified in CONVERT_ON_CAMPUS_SITES within the
# config file. If a site isn't specified there, then this script is skipped and the next data flow 
# script executes immediately

# Define directories
readonly DATA_DIR="/sddata"     # Located on superdarn-data NAS
readonly SOURCE="${DATA_DIR}/${RADAR_ID}_holding_dir"
readonly DEST="${DATA_DIR}/${RADAR_ID}_data"
readonly PROBLEM_FILES_DEST="${DATA_DIR}/conversion_failure"

# Create log file. New file created daily
readonly LOGGING_DIR="${HOME}/logs/convert_on_campus/$(date +%Y/%m)"
mkdir --parents $LOGGING_DIR
readonly LOGFILE="${LOGGING_DIR}/${RADAR_ID}.$(date +%Y%m%d).convert_on_campus.log"
readonly  SUMMARY_DIR="${HOME}/logs/convert_on_campus/summary/$(date +%Y/%m)"
mkdir --parents $SUMMARY_DIR
readonly SUMMARY_FILE="${SUMMARY_DIR}/${RADAR_ID}.$(date -u +%Y%m%d).convert_on_campus_summary.log"

# Telemetry directory for this script and site
readonly TELEMETRY_SCRIPT_DIR="${TELEMETRY_DIR}/${RADAR_ID}/convert_on_campus"

###################################################################################################

exec &>> $LOGFILE # Redirect STDOUT and STDERR to $LOGFILE

printf "################################################################################\n\n" | tee --append $SUMMARY_FILE

printf "Executing $0 on $(hostname) for ${RADAR_ID}\n" | tee --append $SUMMARY_FILE
date --utc "+%Y%m%d %H:%M:%S UTC" | tee --append $SUMMARY_FILE

if [[ " ${CONVERT_ON_CAMPUS_SITES[*]} " =~ " ${RADAR_ID} " ]]; then

    # Get status info on data_flow and pyDARNio repos
    printf "data_flow: $(git -C ${HOME}/data_flow status | grep "On branch"), last commit: \
            $(git -C ${HOME}/data_flow log -1 --format="%h %cd" --date=iso)\n" | tee --append $SUMMARY_FILE
    printf "pyDARNio: $(git -C ${HOME}/pyDARNio status | grep "On branch"), last commit: \
            $(git -C ${HOME}/pyDARNio log -1 --format="%h %cd" --date=iso)\n" | tee --append $SUMMARY_FILE

    printf "Conversion directory: $DATA_DIR\n\n"

    RAWACF_CONVERT_FILES=$(find "${SOURCE}" -maxdepth 1 -name "*rawacf.(hdf5|h5)" -type f)
    RAWACF_DMAP_FILES=$(find "${SOURCE}" -maxdepth 1 -name "*rawacf" -type f)

    if [[ -n $RAWACF_CONVERT_FILES ]]; then
        printf "Converting the following files:\n"
        printf '%s\n' "${RAWACF_CONVERT_FILES[@]}"
    else
        printf "No files to be converted.\n" | tee --append $SUMMARY_FILE
    fi

    # Convert HDF5 files to dmap then move to the proper directories
    for f in $RAWACF_CONVERT_FILES
    do
        printf "\nConverting ${f}\n"
        printf "python3 borealis_to_dmap.py $(basename ${f})\n"
        python3 "${HOME}/data_flow/campus/borealis_to_dmap.py" $f # Creates a new dmap file
        ret=$?
        if [[ $ret -eq 0 ]]; then
            # Move the resulting files if all was successful
            dmap_file=$(get_dmap_name $f)

            mv --verbose $dmap_file $DEST
            mv --verbose $f $DEST
            printf "Successfully converted: ${f}\n" | tee --append $SUMMARY_FILE
        else
            error="File failed to convert to dmap: ${f}\n"
            printf "${error}" | tee --append $SUMMARY_FILE

            message="$(date +'%Y%m%d %H:%M:%S')   convert_on_campus ${RADAR_ID} - ${error}"
            alert_slack "${message}" "${SLACK_DATAFLOW_WEBHOOK}"

            mv --verbose $f $PROBLEM_FILES_DEST
        fi
    done

    # For dmap files received straight from site, just move to the correct directory.
    if [[ -n $RAWACF_DMAP_FILES ]]; then
        printf "Moving the following files:\n"
        printf '%s\n' "${RAWACF_DMAP_FILES[@]}"
    else
        printf "No dmap files to be moved.\n" | tee --append $SUMMARY_FILE
    fi

    for dmap_file in $RAWACF_DMAP_FILES
    do
        mv --verbose $dmap_file $DEST
    done
else
    printf "\nNot converting files for $RADAR_ID.\n" | tee --append $SUMMARY_FILE
fi

printf "\nFinished $(basename $0). End time: $(date --utc "+%Y%m%d %H:%M:%S UTC")\n\n" | tee --append $SUMMARY_FILE

# Sync summary log file with telemetry
printf "Syncing $(basename $SUMMARY_FILE) to $TELEMETRY:$TELEMETRY_SCRIPT_DIR\n\n"
rsync --archive --rsh="$TELEMETRY_RSH" $SUMMARY_FILE $TELEMETRY:$TELEMETRY_SCRIPT_DIR

exit
